name: bakwaas_fm
description: A simple mockup app
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  uni_links: ^0.5.1
  http: ^1.2.1
  audioplayers: ^6.0.0
  url_launcher: ^6.1.5

flutter:
  uses-material-design: true
